version: 2
jobs:
  build:
    working_directory: ~/action-postgres-setup
    docker:
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - run:
          name: Database Setup
          command: |
            pgbench -U postgres -i -h localhost -d postgres
            pgbench -U postgres -h localhost -c 10 -T 30 -S -n
