version: 2
jobs:
  build:
    working_directory: ~/action-postgres-setup
    docker:
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database Setup
          command: |
            pgbench -U postgres -i -d postgres
            pgbench -U postgres -c 10 -T 30 -S -n
