name: Test

on:
  push

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
    name: Test the Postgres Setup Action
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up postgres
        uses: ableco/action-postgres-setup@v1
        with:
          postgres-version: 11
      - name: Initialize pgbench
        run: |
          sudo rm /usr/bin/pgbench
          sudo ln -s /usr/lib/postgresql/11/bin/pgbench /usr/bin/pgbench
          pgbench -i -p 5432 -d postgres
          pgbench -c 100 -T 300 -S -n
